# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2UsMf2f-uthKWWjkf9urPnaWU3ooNLZ
"""

#ETE PORTO DIGITAL
PROFESSOR CLOVES ROCHA
#ESTUDANTE: JOSÉ CARLOS CAVALCANTI

nomes = ['Ana', 'Bruno', 'Carlos']
for n in nomes:
  print(n)